# Generated by Django 2.1 on 2018-09-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='カテゴリを識別するための名前', max_length=20, verbose_name='カテゴリ名')),
                ('description', models.CharField(blank=True, help_text='カテゴリの説明文', max_length=64, verbose_name='説明文')),
            ],
        ),
    ]
