# Generated by Django 2.1 on 2018-10-14 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='質問に対してその人に対して持っている印象の内容', max_length=42, verbose_name='内容')),
                ('posted_at', models.DateTimeField(auto_now_add=True, help_text='投稿された日', verbose_name='投稿日')),
                ('is_collaged', models.BooleanField(default=False, help_text='collageされた場合画面には表示させないためにTrueにする', verbose_name='変更されているか')),
            ],
            options={
                'verbose_name': 'Impression',
                'verbose_name_plural': 'Impressions',
                'ordering': ('-posted_at',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=42)),
                ('appeared_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_personal', models.BooleanField(default=False, help_text='\n                  ユーザが独自に作成したものであればTrue,\n                  運営が作成したものならFalse\n                  ', verbose_name='個人的なものか')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rev_question', to='categories.Category')),
                ('user', models.ManyToManyField(related_name='rev_question', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddField(
            model_name='impression',
            name='question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rev_impression', to='portraits.Question'),
        ),
        migrations.AddField(
            model_name='impression',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rev_impression', to=settings.AUTH_USER_MODEL),
        ),
    ]
