# Generated by Django 2.1 on 2018-09-25 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portraits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearsay',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rev_hearsay', to=settings.AUTH_USER_MODEL),
        ),
    ]
