# Generated by Django 2.2 on 2020-04-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portraits', '0002_impression_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='impression',
            name='impression_img_url',
            field=models.URLField(blank=True, help_text='シェア画像のCloudinaryURL', verbose_name='impression_img_url'),
        ),
    ]
