# Generated by Django 2.1.5 on 2019-06-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portraits', '0002_auto_20181028_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impression',
            name='user',
        ),
    ]
