# Generated by Django 2.1.5 on 2019-10-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portraits', '0004_impression_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_personal',
            field=models.BooleanField(default=False, help_text='\n                  ユーザが独自に作成したものであればTrue,\n                  運営が作成したものならFalse\n                  ', verbose_name='個人的なものか'),
        ),
    ]
