# Generated by Django 2.1 on 2018-09-24 03:23

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('accounts', '0001_initial'), ('accounts', '0002_auto_20180919_2210'), ('accounts', '0003_auto_20180919_2215'), ('accounts', '0004_montageuser_is_admin'), ('accounts', '0005_montageuser_is_staff'), ('accounts', '0006_montageuser_is_superuser'), ('accounts', '0007_auto_20180919_2238'), ('accounts', '0008_auto_20180919_2241'), ('accounts', '0009_auto_20180919_2244'), ('accounts', '0010_auto_20180920_0040')]

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MontageUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'min': '名前が短すぎます', 'unique': 'すでに存在しているユーザ名です'}, help_text='@で始まるユーザ名', max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[a-zA-Z0-9_]+$', 'ユーザー名には半角英数、アンダースコアだけ使えます')], verbose_name='ユーザ名')),
                ('email', models.EmailField(blank=True, help_text='255字以内.空文字可', max_length=255, verbose_name='メールアドレス')),
                ('display_name', models.CharField(blank=True, help_text='30文字以内', max_length=30, verbose_name='プロフィール名')),
                ('date_of_birth', models.DateField(blank=True, help_text='%yy-%MM-%dd形式.空白可', null=True, verbose_name='誕生日')),
                ('mail_confirmed', models.BooleanField(default=False, help_text='確認済みの場合True', verbose_name='メールアドレスが確認済みか')),
                ('twitter_id', models.CharField(blank=True, help_text='@から始まる名前.@は不要', max_length=150, verbose_name='TwitterID')),
                ('is_active', models.BooleanField(default=True, help_text='is_active', verbose_name='退会していないか?')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='created_date', verbose_name='登録日時')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='modified_date', verbose_name='更新日時')),
                ('is_staff', models.BooleanField(default=False, help_text='is_staff', verbose_name='スタッフか?')),
                ('is_superuser', models.BooleanField(default=False, help_text='is_superuser', verbose_name='管理者か?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
                ('first_name', models.CharField(blank=True, default='', help_text='first_name', max_length=30, verbose_name='名字')),
                ('last_name', models.CharField(blank=True, default='', help_text='last_name', max_length=30, verbose_name='下の名前')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.MontageUserManager()),
            ],
        ),
    ]
