# Generated by Django 2.1.2 on 2018-11-03 08:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_squashed_0010_auto_20180920_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='montageuser',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='プロフィール画像', max_length=255, verbose_name='profile_image'),
        ),
    ]
