# Generated by Django 2.1.2 on 2018-11-04 00:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_montageuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montageuser',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='profile_image'),
        ),
    ]
