# Generated by Django 2.1.2 on 2018-11-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181104_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montageuser',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='プロフィール画像', upload_to='', verbose_name='profile_image'),
        ),
    ]
