# Generated by Django 2.1.5 on 2019-06-20 10:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181104_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montageuser',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='プロフィール画像', max_length=255, null=True, verbose_name='profile_image'),
        ),
    ]
