# Generated by Django 2.1.5 on 2019-06-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190620_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montageuser',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='プロフィール画像', null=True, upload_to='', verbose_name='profile_image'),
        ),
    ]
