# Generated by Django 2.1.5 on 2019-06-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190620_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='montageuser',
            name='twitter_id',
        ),
    ]
