# Generated by Django 2.1.5 on 2019-06-20 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portraits', '0003_remove_impression_user'),
        ('accounts', '0008_remove_montageuser_twitter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='montageuser',
            name='impressions',
            field=models.ForeignKey(blank=True, help_text='回答', null=True, on_delete=django.db.models.deletion.CASCADE, to='portraits.Impression'),
        ),
    ]
