# Generated by Django 2.1.5 on 2019-06-20 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_montageuser_impressions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='montageuser',
            name='impressions',
        ),
    ]
