# Generated by Django 2.1.5 on 2019-09-04 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('accounts', '0011_auto_20190818_1538'), ('accounts', '0012_auto_20190818_1559'), ('accounts', '0013_auto_20190904_2035'), ('accounts', '0014_remove_montageuser_username'), ('accounts', '0015_montageuser_username'), ('accounts', '0016_auto_20190904_2044')]

    dependencies = [
        ('accounts', '0010_remove_montageuser_impressions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='montageuser',
            name='username',
        ),
        migrations.AddField(
            model_name='montageuser',
            name='identifier_id',
            field=models.CharField(default=None, help_text='auth0のユーザID', max_length=30, unique=True, verbose_name='ユーザID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='montageuser',
            name='display_name',
            field=models.CharField(error_messages={'max': '名前が長すぎます'}, help_text='30文字以内', max_length=30, verbose_name='プロフィール名'),
        ),
        migrations.RemoveField(
            model_name='montageuser',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='montageuser',
            name='profile_img_url',
            field=models.URLField(blank=True, help_text='プロフィール画像のURL', null=True, verbose_name='profile_img_url'),
        ),
        migrations.RemoveField(
            model_name='montageuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='montageuser',
            name='mail_confirmed',
        ),
        migrations.AddField(
            model_name='montageuser',
            name='username',
            field=models.CharField(error_messages={'min': '名前が短すぎます', 'unique': 'すでに存在しているユーザ名です'}, help_text='@で始まるユーザ名', max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[a-zA-Z0-9_]+$', 'ユーザー名には半角英数、アンダースコアだけ使えます')], verbose_name='ユーザ名'),
        ),
    ]
