# Generated by Django 2.1.5 on 2019-10-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190818_1538_squashed_0016_auto_20190904_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='montageuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='montageuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='montageuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='montageuser',
            name='last_name',
        ),
    ]
